DROP TABLE IF EXISTS GENRES;
CREATE TABLE IF NOT EXISTS GENRES (ID BIGINT auto_increment PRIMARY KEY, GENRE_NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE IF NOT EXISTS AUTHORS (ID BIGINT auto_increment PRIMARY KEY, FULL_NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE IF NOT EXISTS BOOKS (ISBN VARCHAR(17) PRIMARY KEY, TITLE VARCHAR(1000) NOT NULL);

DROP TABLE IF EXISTS ASSOC;
CREATE TABLE IF NOT EXISTS ASSOC (ISBN VARCHAR(17) NOT NULL, EXTERNAL_ID BIGINT NOT NULL, EXTERNAL_CLASS VARCHAR(255) NOT NULL,
PRIMARY KEY (ISBN, EXTERNAL_ID, EXTERNAL_CLASS));