spring:
  datasource:
    url: jdbc:h2:file:~/IdeaProjects/Otus/lesson/2022-08-otus-spring-kokorev/data/collectorio
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        default_batch_fetch_size: 10
        batch_fetch_style: PADDED
logging:
  level:
    root: INFO