spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/createAclSchemaPostgres.sql
      data-locations: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/collectorio?currentSchema=collectorio
    username: postgres
    password: postgres
