spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/collectorio?currentSchema=collectorio
    username: postgres
    password: postgres
liquibase:
  convertDataTypes: true

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

url:
  forAll: /api/**
  forUser: /api/user/**
  forAdmin: /api/admin/**