spring:
  messages:
    basename: "i18n/message"
    encoding: "UTF-8"
    script:
      spring:
        shell:
          script: false

application:
  locale: ru
  file:
    location: /csv/$locale/test.csv