version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hw17-app_docker"
    ports:
      - "8080:8080"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_SQL_INIT_SCHEMA-LOCATIONS=classpath:sql/schema.postgre.sql
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - network
  postgres:
    image: "postgres:15.1"
    container_name: "postgres-15.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    networks:
      - network
networks:
  network: