DROP TABLE IF EXISTS GENRES;
CREATE TABLE IF NOT EXISTS GENRES (ID BIGINT PRIMARY KEY auto_increment, GENRE_NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE IF NOT EXISTS AUTHORS (ID BIGINT PRIMARY KEY auto_increment, FULL_NAME VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE IF NOT EXISTS BOOKS (ID BIGINT PRIMARY KEY auto_increment, ISBN VARCHAR(17) NOT NULL, TITLE VARCHAR(1000) NOT NULL);

DROP TABLE IF EXISTS BOOK_AUTHORS;
CREATE TABLE IF NOT EXISTS BOOK_AUTHORS (BOOK_ISBN VARCHAR(17) NOT NULL, AUTHOR_ID BIGINT NOT NULL,
PRIMARY KEY (BOOK_ISBN, AUTHOR_ID));

DROP TABLE IF EXISTS BOOK_GENRES;
CREATE TABLE IF NOT EXISTS BOOK_GENRES (BOOK_ISBN VARCHAR(17) NOT NULL, GENRE_ID BIGINT NOT NULL,
PRIMARY KEY (BOOK_ISBN, GENRE_ID));

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE IF NOT EXISTS COMMENTS (ID BIGINT PRIMARY KEY auto_increment, BOOK_ISBN VARCHAR(17) NOT NULL, COMMENT_TEXT VARCHAR(1000) NOT NULL);