spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/aclBook
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 10
        batch_fetch_style: PADDED